export const translations = {
  en: {
    appName: "Nashik LocalKart",
    welcomeMessage: "Welcome to Nashik LocalKart",
    tagline: "Your one-stop portal for local vendors in Mhasrul, Nashik.",
    exploreVendors: "Explore Vendors",
    login: "Login",
    signup: "Sign Up",
    logout: "Logout",
    home: "Home",
    marketplace: "Marketplace",
    dashboard: "Dashboard",
    adminPanel: "Admin Panel",
    language: "Language",
    english: "English",
    marathi: "Marathi",
    vendorLogin: "Vendor Login",
    customerLogin: "Customer Login",
    vendorSignup: "Vendor Signup",
    customerSignup: "Customer Signup",
    email: "Email",
    password: "Password",
    name: "Name",
    phone: "Phone",
    address: "Address",
    shopName: "Shop Name",
    category: "Category",
    findVendors: "Find Vendors",
    searchByCategory: "Search by category...",
    searchByArea: "Search by area...",
    allCategories: "All Categories",
    allAreas: "All Areas",
    viewOnMap: "View on Map",
    getDirections: "Get Directions",
    shopDetails: "Shop Details",
    ownerName: "Owner Name",
    contactInfo: "Contact Info",
    workingHours: "Working Hours",
    paymentMethods: "Payment Methods Accepted",
    aboutShop: "About the Shop",
    backToMarketplace: "Back to Marketplace",
    vendorDashboard: "Vendor Dashboard",
    editProfile: "Edit Profile",
    customerDashboard: "Customer Dashboard",
    favoriteShops: "Favorite Shops",
    welcome: "Welcome",
    vendorApproval: "Vendor Approval",
    approve: "Approve",
    reject: "Reject",
    status: "Status",
    pending: "Pending",
    approved: "Approved",
    rejected: "Rejected",
    // FIX: Add missing translations for chatbot component.
    sources: "Sources",
    chatWithUs: "Chat with us",
    chatPlaceholder: "Ask me anything...",
  },
  mr: {
    appName: "नाशिक लोकलकार्ट",
    welcomeMessage: "नाशिक लोकलकार्टमध्ये आपले स्वागत आहे",
    tagline: "म्हसरूळ, नाशिक येथील स्थानिक विक्रेत्यांसाठी आपले वन-स्टॉप पोर्टल.",
    exploreVendors: "विक्रेते शोधा",
    login: "लॉगिन",
    signup: "साइन अप",
    logout: "लॉगआउट",
    home: "मुख्यपृष्ठ",
    marketplace: "बाजारपेठ",
    dashboard: "डॅशबोर्ड",
    adminPanel: "ऍडमिन पॅनेल",
    language: "भाषा",
    english: "इंग्रजी",
    marathi: "मराठी",
    vendorLogin: "विक्रेता लॉगिन",
    customerLogin: "ग्राहक लॉगिन",
    vendorSignup: "विक्रेता साइनअप",
    customerSignup: "ग्राहक साइनअप",
    email: "ईमेल",
    password: "पासवर्ड",
    name: "नाव",
    phone: "फोन",
    address: "पत्ता",
    shopName: "दुकानाचे नाव",
    category: "श्रेणी",
    findVendors: "विक्रेते शोधा",
    searchByCategory: "श्रेणीनुसार शोधा...",
    searchByArea: "परिसानुसार शोधा...",
    allCategories: "सर्व श्रेणी",
    allAreas: "सर्व परिसर",
    viewOnMap: "नकाशावर पहा",
    getDirections: "दिशा मिळवा",
    shopDetails: "दुकानाची माहिती",
    ownerName: "मालकाचे नाव",
    contactInfo: "संपर्क माहिती",
    workingHours: "कामाचे तास",
    paymentMethods: "स्वीकृत पेमेंट पद्धती",
    aboutShop: "दुकानाबद्दल",
    backToMarketplace: "बाजारपेठेत परत जा",
    vendorDashboard: "विक्रेता डॅशबोर्ड",
    editProfile: "प्रोफाइल संपादित करा",
    customerDashboard: "ग्राहक डॅशबोर्ड",
    favoriteShops: "आवडती दुकाने",
    welcome: "स्वागत आहे",
    vendorApproval: "विक्रेता मंजूरी",
    approve: "मंजूर करा",
    reject: "नाकारा",
    status: "स्थिती",
    pending: "प्रलंबित",
    approved: "मंजूर",
    rejected: "नाकारले",
    // FIX: Add missing translations for chatbot component.
    sources: "स्रोत",
    chatWithUs: "आमच्याशी चॅट करा",
    chatPlaceholder: "काहीही विचारा...",
  }
};

export const VENDOR_CATEGORIES = ["Food", "Grocery", "Tailor", "Electronics", "Chemist", "General Store", "Cafe"];
export const NASHIK_AREAS = ["Mhasrul", "Panchavati", "Tidke Nagar", "Gangapur Road", "College Road"];
